### PR TITLE
Frontend - Requests and Download

### PR DESCRIPTION
**Pull request by FlyteWizard**
Adding the proper request with data and user experience.

### CODE REVIEW

**Comment by malcolmseyd** [comment]
FYI I just changed `schema.js` to work with the AI, I made a new `frontend` object that hopefully clarifies what you should be sending

[link here](https://github.com/malcolmseyd/coop-report-generator/commit/2acab8f467a75b7b8df2f73caac8247f90c95b94#diff-1129f63aded250bafe587b53e8c574f25c7fcb8247a43111f01ab70d23fdbd48R48-R86)

**Comment by FlyteWizard** [comment]
@malcolmseyd 

I'm running into environment errors: `throw new Error(${name} is a required envvar)` and `Error: OPENAI_API_KEY is a required envvar`. Let me know how the `.env` file is structured.

I'm hoping the above fixes this new error `XMLHttpRequest cannot load http://localhost:8080/gen due to access control checks.`

**Comment by malcolmseyd** [comment]
Oh shoot I think I broke the Docker environment when I integrated the OpenAI code. Try passing an envvar named OPENAI_API_KEY to the docker container when you start it.

**Comment by FlyteWizard** [comment]
This now works, and produces a report with the provided input 👍 

[uvic-engr-work-term-report.pdf](https://github.com/malcolmseyd/coop-report-generator/files/8942040/uvic-engr-work-term-report.pdf)

**Comment by FlyteWizard** [comment]
@malcolmseyd Merge whenever you are good with the PR (I can't merge).

I have a few more things to accomplish on the frontend to create a better user experience, and then I'll update the README.

**Review by malcolmseyd — APPROVED** [review]
Dog LGTM

**Pull request merged**
